# Generated by Django 5.1.1 on 2024-09-18 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
